# Note that the postgresql server package install provides the
# "postgres" user account and group.
  - name: install packages
    apt:
      state: latest
      name: "{{ item }}"
    with_items:
      - postgresql-9.3
      - postgresql-client-9.3
      - python-psycopg2 # for ansible itself
  - name: set up www-data DB role
    sudo_user: postgres
    postgresql_user:
      name: www-data
      password: www-data
  - name: set up todoserver DB
    sudo_user: postgres
    postgresql_db:
      name: todoserver
      owner: www-data
      state: present
      encoding: 'UTF-8'
  - name: create initial database tables
    script: create_todoserver_tables.sh creates=/srv/FLAGS/todoapi/create_initial_db_tables