- hosts: apiserver-dev
  remote_user: vagrant
  sudo: true
  tasks:
    - apt:
        state: latest
        name: "{{ item }}"
      with_items:
        # apache webserver
        - apache2-mpm-worker
        - apache2-utils
        - git
        - realpath
    # Hack to set up 3.4 pyvenv on ubuntu 14.04 - see https://gist.github.com/denilsonsa/21e50a357f2d4920091e
    - script: py34_venv_with_pip.sh /srv/VENV/todoapi creates=/srv/VENV/todoapi
      notify:
        restart apache
    - pip:
        requirements: /srv/todoapi/requirements.txt
        executable: /srv/VENV/todoapi/bin/pip
      notify:
        restart apache
    - copy:
        src: ../vhost.conf
        dest: /etc/apache2/sites-available/todo-server.vhost
    - file:
        state: link
        src: /etc/apache2/sites-available/todo-server.vhost
        dest: /etc/apache2/sites-enabled/todo-server.vhost
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted