---
- name: todo server
  hosts: apiserver-dev
  roles:
    - wsgiexpress
  remote_user: vagrant
  sudo: true
  gather_facts: no
  pre_tasks:
    - apt:
        state: present
        name: apache2-mpm-worker
  tasks:
    - name: install and update packages
      apt:
        state: present
        name: "{{ item }}"
      with_items:
        - apache2-utils
        - git
        - realpath


    - name: Deploy directory exists
      file:
        path: /srv/FLAGS/todoapi
        state: directory

    - include: postgres_setup.yml

    # todoapi venv
    - name: todo-server virtual environment exists
      script: py34_venv_with_pip.sh /srv/VENV/todoapi creates=/srv/VENV/todoapi
      notify:
        - restart apache
    - name: todo-server venv requirements satisfied
      pip:
        requirements: /srv/todoapi/requirements.txt
        executable: /srv/VENV/todoapi/bin/pip
      notify:
        restart apache
    - name: todo-server vhost available
      file:
        state: link
        src: /srv/todoapi/apache/vhost.conf
        dest: /etc/apache2/sites-available/todo-server.conf
      notify:
        - restart apache
    - name: todo-server vhost enabled
      file:
        state: link
        src: /etc/apache2/sites-available/todo-server.conf
        dest: /etc/apache2/sites-enabled/todo-server.conf
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
