- hosts: apiserver-dev
  remote_user: vagrant
  sudo: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
    - name: install packages
      apt:
        state: latest
        name: "{{ item }}"
      with_items:
        # apache webserver
        - apache2-mpm-worker
        - apache2-utils
        - git
        - realpath

    - include: wsgi_express.yml

    # todoapi venv
    - script: py34_venv_with_pip.sh /srv/VENV/todoapi creates=/srv/VENV/todoapi
      notify:
        restart apache
    - pip:
        requirements: /srv/todoapi/requirements.txt
        executable: /srv/VENV/todoapi/bin/pip
      notify:
        restart apache
    - file:
        state: link
        src: /srv/todoapi/vhost.conf
        dest: /etc/apache2/sites-available/todo-server.conf
    - file:
        state: link
        src: /etc/apache2/sites-available/todo-server.conf
        dest: /etc/apache2/sites-enabled/todo-server.conf
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted